CREATE TABLE IF NOT EXISTS User (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  nickname VARCHAR(16) BINARY UNIQUE DEFAULT NULL COMMENT '昵称',
  password VARCHAR(64) BINARY NOT NULL COMMENT '用户密码,加密',
  email VARCHAR(64) BINARY UNIQUE NOT NULL COMMENT '用户邮箱',
  avatar VARCHAR(256) DEFAULT NULL COMMENT '用户头像地址',
  gender BOOL DEFAULT 0 COMMENT '性别，默认男',
  city VARCHAR(32) DEFAULT NULL COMMENT '所在城市',
  summary TEXT DEFAULT NULL COMMENT '个人简介',
  created_at TIMESTAMP DEFAULT current_timestamp COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT current_timestamp ON UPDATE current_timestamp COMMENT '最后一次更新时间',
  PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS Article (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  title VARCHAR(128) BINARY UNIQUE NOT NULL COMMENT '标题',
  content TEXT NOT NULL COMMENT '文章内容',
  views INT UNSIGNED DEFAULT 0 COMMENT '文章阅读量',
  public BOOL DEFAULT 1 COMMENT '是否公开，默认公开，私密则为0',
  created_at TIMESTAMP DEFAULT current_timestamp COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT current_timestamp ON UPDATE current_timestamp COMMENT '最后一次更新时间',
  PRIMARY KEY (id),
  INDEX title_index(title),
  INDEX public_index(public)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS Label (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  label VARCHAR(16) BINARY UNIQUE NOT NULL COMMENT '具体标签',
  created_at TIMESTAMP DEFAULT current_timestamp COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT current_timestamp ON UPDATE current_timestamp COMMENT '最后一次更新时间',
  PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS ArticleLabel(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  article_id INT UNSIGNED NOT NULL COMMENT '文章表的id',
  label_id INT UNSIGNED NOT NULL COMMENT '标签表的id',
  PRIMARY KEY (id),
  UNIQUE KEY (article_id, label_id),
  CONSTRAINT a_article_fk FOREIGN KEY(article_id) REFERENCES Article(id) ON DELETE CASCADE on UPDATE CASCADE,
  CONSTRAINT a_label_fk FOREIGN KEY (label_id) REFERENCES Label(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS Comment(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  article_id INT NOT NULL COMMENT '评论所属的文章',
  user_id INT UNSIGNED DEFAULT NULL COMMENT '用户ID,匿名评论为null',
  reply_id INT UNSIGNED DEFAULT NULL COMMENT '被回复的评论的ID',
  avatar VARCHAR(256) NOT NULL COMMENT '匿名评论者的头像URL',
  content TEXT DEFAULT NULL COMMENT '评论的正文',
  created_at TIMESTAMP DEFAULT current_timestamp COMMENT '创建时间',
  PRIMARY KEY (id),
  INDEX article_id_index(article_id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;